name: Android CI

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [30, 33, 34]
        target: [default, google_apis]
    steps:
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          java-version: '17'

      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM (not applicable on macOS)
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Launch Emulator
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus_6
          emulator-options: -no-audio -no-boot-anim -no-window
          script: |
            echo "Starting emulator..."

      - name: Check Emulator Status and Print Message
        run: |
          # Wait for emulator to start
          adb wait-for-device
          
          # Poll for emulator status
          until adb shell 'getprop sys.boot_completed' | grep -m 1 '1'; do
            echo "Waiting for emulator to fully boot..."
            sleep 15
          done
          
          # Print a colorful message
          echo -e "\033[0;32mEmulator is online and ready!\033[0m"

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: x86_64
          profile: Nexus_6
          script: -|
            echo "Henlo my fren [ 1 ]"
            echo "Henlo my fren [ 2 ]"







