name: Android CI

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [34]
        target: [google_apis]
    steps:
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
      - name: Clear SDK Repository Cache
        run: |
          rm -rf $HOME/.android/cache
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: "zulu"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          java-version: '17'

      - name: checkout
        uses: actions/checkout@v4

      - name: Enable KVM (not applicable on macOS)
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install System Image and Create AVD
        run: |
          sdkmanager --install "system-images;android-34;google_apis;arm64-v8a"
          echo "no" | avdmanager create avd -n testAVD -k "system-images;android-34;google_apis;arm64-v8a" --force
  
      - name: Launch and Monitor Emulator
        run: |
          $ANDROID_HOME/emulator/emulator -avd testAVD -no-audio -no-boot-anim -no-window -verbose &
          EMULATOR_PID=$!
          adb wait-for-device
          until adb shell 'getprop sys.boot_completed' | grep -m 1 '1'; do
            echo "Waiting for emulator to fully boot..."
            sleep 15
          done
          echo -e "\033[0;32mEmulator is online and ready!\033[0m"
          kill $EMULATOR_PID
        timeout-minutes: 15  # Increased timeout for emulator launch and setup

#      - name: Run tests
#        uses: reactivecircus/android-emulator-runner@v2
#        with:
#          api-level: ${{ matrix.api-level }}
#          target: ${{ matrix.target }}
#          arch: x86_64
#          profile: Nexus_6
#          script: -|
#            echo "Henlo my fren [ 1 ]"
#            echo "Henlo my fren [ 2 ]"







