name: Android AVD Setup

on:
  push:
    branches:
      - "*"

jobs:
  setup_avd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Environment and AVD
        run: |
          # Install SDKMAN
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          
          # Setup Java with SDKMAN
          sdk install java 8.0.402-amzn
          sdk use java 8.0.402-amzn
          
          # Install Android SDK
          sudo apt-get update
          sudo apt-get install -y android-sdk
          
          # Set Environment Variables
          echo "ANDROID_HOME=/usr/lib/android-sdk" >> $GITHUB_ENV
          echo "$ANDROID_HOME/tools/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          
          # Install System Image and Create AVD
          sudo $ANDROID_HOME/tools/bin/sdkmanager "system-images;android-24;default;x86"
          echo "no" | sudo $ANDROID_HOME/tools/bin/avdmanager create avd --name maestro_shard_1 --abi "x86" --package "system-images;android-24;default;x86" --force
          
          # Launch Emulator
          sudo $ANDROID_HOME/emulator/emulator -avd maestro_shard_1 -no-audio -no-boot-anim -no-window &
          sleep 30 # Wait for emulator to start

